#ifndef KEYWORDS_H
#define KEYWORDS_H

// SQL Keywords
#define KEYWORD_CREATE "CREATE"
#define KEYWORD_DROP "DROP"
#define KEYWORD_TABLE "TABLE"
#define KEYWORD_SELECT "SELECT"
#define KEYWORD_INSERT "INSERT"
#define KEYWORD_DELETE "DELETE"
#define KEYWORD_FROM "FROM"
#define KEYWORD_INTO "INTO"
#define KEYWORD_VALUES "VALUES"

// Data Types
#define KEYWORD_INT "INT"
#define KEYWORD_INTEGER "INTEGER"
#define KEYWORD_REAL "REAL"
#define KEYWORD_TEXT "TEXT"
#define KEYWORD_BOOLEAN "BOOLEAN"

#endif 
