name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make valgrind
    
    - name: Build main executable
      run: make main
    
    - name: Run unit tests
      run: |
        make test_hashmap
        make test_parser
        make test_tokenizer
    
    - name: Run integration tests
      run: make test_integration
      
    - name: Clean up
      run: make clean
